CREATE TABLE ARTIST (
ID SERIAL PRIMARY KEY,
NAME VARCHAR(150) NOT NULL,
TIPO VARCHAR(25) NOT NULL,
MEMBROS INT,
GENERO_MUSICAL VARCHAR(50) NOT NULL,
NACIONALIDADE VARCHAR(50) NOT NULL,
ANO_DE_INICIO INT NOT NULL,
MUSICA_MAIS_FAMOSA VARCHAR(50) NOT NULL,
ATIVO BOOLEAN DEFAULT TRUE
);

