SELECT * FROM ARTIST;

SELECT COUNT(*) AS TOTAL_ARTISTAS FROM ARTIST;

SELECT NAME, MUSICA_MAIS_FAMOSA FROM ARTIST WHERE NACIONALIDADE = 'brasileira';

SELECT NAME, MUSICA_MAIS_FAMOSA FROM ARTIST WHERE GENERO_MUSICAL = 'rap' AND ID = 3;