SELECT * FROM JOGOS_MODO_HISTORIA;

SELECT COUNT(*) AS TOTAL_JOGOS FROM JOGOS_MODO_HISTORIA;

SELECT NOME, GENERO, ANO_DE_LANCAMENTO FROM JOGOS_MODO_HISTORIA WHERE NOTA > 9.0;

SELECT NOME, DESENVOLVEDORA, NOTA FROM JOGOS_MODO_HISTORIA WHERE TEVE_CONTINUACAO = TRUE AND ANO_DE_LANCAMENTO >= 2015;

SELECT NOME, ANO_DE_LANCAMENTO FROM JOGOS_MODO_HISTORIA WHERE ID = 5;

